//
// Resource header file generated by CTRPP tool, contains STRINGID definition.
//
#define IDS_provider_00007          7
#define IDS_provider_00005          5
#define IDS_provider_00006          6
#define IDS_provider_00003          3
#define IDS_provider_00001          1
#define IDS_provider_00002          2

