// <auto-generated />

using System;
using Keys.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

namespace Keys.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Keys.Data.Entities.Key", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ContentKey")
                        .IsRequired();

                    b.Property<int>("KeyType");

                    b.Property<Guid>("Kid");

                    b.Property<Guid>("Uuid");

                    b.HasKey("Id");

                    b.HasIndex("KeyType", "Kid")
                        .IsUnique();

                    b.HasIndex("KeyType", "Uuid")
                        .IsUnique();

                    b.ToTable("Keys");
                });
#pragma warning restore 612, 618
        }
    }
}
